//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeninTravel_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_des_destinos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tm_des_destinos()
        {
            this.tm_vi2_viajes = new HashSet<tm_vi2_viajes>();
        }
    
        public int ID { get; set; }
        public int cod_viaje { get; set; }
        public int nro_plazas { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public decimal precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tm_vi2_viajes> tm_vi2_viajes { get; set; }
    }
}
