//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeninTravel_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_via_viajeros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tm_via_viajeros()
        {
            this.tm_vi2_viajes = new HashSet<tm_vi2_viajes>();
        }
    
        public int id { get; set; }
        public string via_nombre { get; set; }
        public string via_apellido { get; set; }
        public string via_ci { get; set; }
        public string via_pasaporte { get; set; }
        public string via_direccion { get; set; }
        public string via_telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tm_vi2_viajes> tm_vi2_viajes { get; set; }
    }
}
